# Generated by Django 6.0.2 on 2026-03-24 10:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_travelpackage_detailed_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbooking',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='last_payment_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='razorpay_last_event_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='travelbooking',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay (Online Payment)'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash at Office')], default='upi', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('advance_paid', 'Advance Paid'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
