# Generated by Django 6.0.2 on 2026-03-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_travelbooking_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbooking',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='bus_seats_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='train_tickets_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
