# Generated by Django 6.0.2 on 2026-04-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='subject',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='contact_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
