# Generated by Django 6.0.2 on 2026-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userfeedback_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='discovery_source',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='satisfaction_score',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
